AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    trip

    Rest API to manage a Data Lake of trip links

Globals:
    Function:
        Timeout: 50
        MemorySize: 512
        Environment:
          Variables:
            TABLE_NAME: !Ref TripTable
            ENDPOINT_OVERRIDE: ""

Resources:
  
  GetTripsByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: ./target/onpaty-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.rws.handler.GetTripsByCity::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTripRecord:
         Type: Api
         Properties:
           Path: /trip/{city}
           Method: get
           RequestParameters:
            - method.request.querystring.city
  GetTripsByCountryFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: ./target/onpaty-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.rws.handler.GetTripsByCountry::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTripRecord:
         Type: Api
         Properties:
           Path: /trip/country/{country}
           Method: get
           RequestParameters:
            - method.request.querystring.country  
  CreateTripRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
     CodeUri: ./target/onpaty-0.0.1-SNAPSHOT-jar-with-dependencies.jar
     Handler: br.com.rws.handler.CreateTripRecord::handleRequest
     Runtime: java8
     Policies:
       - DynamoDBCrudPolicy:
           TableName: !Ref TripTable     
     Events:
       CreateTripRecord:
         Type: Api
         Properties:
           Path: /trip
           Method: post
                      
  StudyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trip
      AttributeDefinitions:
        - AttributeName: country
          AttributeType: S
        - AttributeName: city
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: reason
          AttributeType: S            
      KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      LocalSecondaryIndexes: 
        - IndexName: tagIndex
          KeySchema: 
            - AttributeName: country
              KeyType: HASH
            - AttributeName: city
              KeyType: RANGE
          Projection:
             ProjectionType: ALL 
        - IndexName: consumedIndex
          KeySchema: 
            - AttributeName: country
              KeyType: HASH
            - AttributeName: reason
              KeyType: RANGE
          Projection:
             ProjectionType: ALL      
      BillingMode: PAY_PER_REQUEST             

Outputs:

    CreateTripRecordFunction:
      Description: "CreateTripRecord Lambda Function ARN"
      Value: !GetAtt CreateTripRecordFunction.Arn
  
     